In [12]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.datasets import make_classification
import numpy as np

In [7]:
X, y = load_iris(return_X_y=True)
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42)

In [13]:
X, y = make_classification()

In [15]:
np.where(y == 0)[0]

array([ 1,  2,  5,  6, 13, 15, 16, 21, 22, 24, 26, 27, 29, 31, 32, 34, 39,
       43, 44, 45, 46, 47, 49, 50, 51, 53, 56, 57, 58, 59, 61, 62, 64, 69,
       77, 79, 80, 84, 85, 87, 89, 90, 91, 92, 93, 94, 96, 97, 98])

In [3]:
classes, counts = np.unique(y, return_counts=True)
prior = counts / len(y)

In [6]:
classes, counts = np.unique(y, return_counts=True)

In [7]:
counts

array([49, 51])

In [ ]:
class_mask = classes[:, np.newaxis] == y[np.newaxis, :]
class_mask.shape

(2, 100)

In [42]:
counts

array([49, 51])

In [51]:
# Conditional means
means = (
    np.sum(X[np.newaxis, :, :] * class_mask[:, :, np.newaxis], axis=1)
    / counts[:, np.newaxis]
)
means[1]

array([ 0.09199219, -0.46713388,  0.21978177,  0.00964994,  0.0177607 ,
        0.17397336,  0.00583116, -0.04809468, -0.12747124, -0.10169644,
        0.0093886 , -0.0189537 , -0.1849982 ,  0.79938344, -0.17519017,
        0.29184232, -0.01486775,  0.18787809,  0.16059727, -0.29071043])